language: java
jdk:
  - oraclejdk8
before_script: "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./make_credentials.py"
script: 
  - find $HOME/.m2 -name "_remote.repositories" | xargs rm
  - find $HOME/.m2 -name "resolver-status.properties" | xargs rm
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && mvn test || true"

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.m2/repository

# whitelist
branches:
  only:
    - master
