language: java
jdk:
  - oraclejdk8
before_script: "[[ $TRAVIS_PULL_REQUEST == \"false\" ]]"
script:
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && mvn test || true"

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.m2/repository

# whitelist
branches:
  only:
    - master
